import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '../components/Navbar'

import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from '../components/Toaster'
import Footer from '../components/Footer'
import CartContext from '../components/section/CartContext'
import Cart from '../components/Cart'
import { Suspense } from 'react'
import Loader from '../components/section/Loader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' min-h-screen'}>
        <Suspense fallback={<Loader />}>
          <ClerkProvider>
            <CartContext>
              <Navbar />
              <div className="w-full pt-12 min-h-[87vh] relative">
                {children}
              </div>
              <Toaster />
              <Footer />
            </CartContext>
          </ClerkProvider>
        </Suspense>
      </body>
    </html>
  )
}
