import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '../components/Navbar'

import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className + ' min-h-screen'}>
          <Navbar />
          <div className="w-full pt-12 min-h-[87vh]">{children}</div>
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  )
}
