'use client'
import Navbar from '../components/Navbar'
import { SessionProvider } from 'next-auth/react'
import { Session } from 'next-auth'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' min-h-screen'}>
        <SessionProvider session={session}>
          <Navbar />
          <div className="min-h-[90vh]  w-screen">{children}</div>
        </SessionProvider>
      </body>
    </html>
  )
}
